<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Authors>Alex Thomson</Authors>
    <Product>Discord Common</Product>
    <Copyright>© Alex Thomson. All rights reserved.</Copyright>
    <Title>Discord Common</Title>
    <Description>Common Library for Discord.Net</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/LXGaming/Discord.Common</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/LXGaming/Discord.Common</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\icon.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\PACKAGE.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

</Project>
